# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build lab2
      run: |
        cd lab2
        go build -v ./...

    - name: Test lab2
      run: |
        cd lab2
        make test

    - name: Build lab3
      run: |
        cd lab3
        go build -v ./...

    - name: Test lab3
      run: |
        cd lab3
        make test