# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: lab2

on:
  push:
    paths:
      - 'lab2/**'
  pull_request:
    paths:
      - 'lab2/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build lab2
      run: |
        cd lab2
        go build -v ./...

    - name: Test lab2
      run: |
        cd lab2
        make test
