name: lab3

on:
  push:
    paths:
      - 'lab3/**'
  pull_request:
    paths:
      - 'lab3/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build lab3
      run: |
        cd lab3
        go build -v ./...

    - name: Test lab3
      run: |
        cd lab3
        make test
