name: lab4

on:
  push:
    paths:
      - 'lab4/**'
  pull_request:
    paths:
      - 'lab4/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning lab4
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Unit test
      run: |
        cd ./lab4/cmd/lb/
        go test
      
    - name: Build Docker
      run: |
       cd ./lab4/
       docker build -f Dockerfile -t lab-4:v1 .

    - name: Docker compose
      run: |
        cd ./lab4/
        docker-compose up &                                                                                                                            
        sleep 5
        go run ./lab4/cmd/client/client.go &                                                                                                                   
        sleep 10
        pkill client.go
        sleep 5
        pkill docker-compose

    - name: Docker compose integration
      run: |
       cd ./lab4/
       docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test &
       sleep 15
       cd ./lab4/integration/
       go test
       sleep 5
       pkill docker-compose

