name: lab4

on:
  push:
    paths:
      - 'lab4/**'
  pull_request:
    paths:
      - 'lab4/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning lab4
      uses: actions/checkout@v2
      with:
        path: lab4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker
      run: docker build -f Dockerfile -t lab-4:v1 .

    - name: Docker compose
      run: docker-compose up

    - name: Unit test
      run: |
        cd cmd/lb/
        go test

    - name: Docker compose integration
      run: docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test

    - name: Integration test
      run: |
        cd integration/
        go test
